@baseUrl = http://localhost:8090/rpc

###
POST {{baseUrl}}
Content-Type: application/json

{"jsonrpc": "2.0", "method": "Subtract", "params": [42, 23], "id": 1}

###
POST {{baseUrl}}
Content-Type: application/json

{"jsonrpc": "2.0", "method": "Divide", "params": [42, 0], "id": 1}

###
POST {{baseUrl}}
Content-Type: application/json

[
    {"jsonrpc": "2.0", "method": "Divide", "params": [42, 0], "id": 1},
    {"jsonrpc": "2.0", "method": "Subtract", "params": [42, 23], "id": 2},
    {"foo": "boo"},
    {"jsonrpc": "2.0", "method": "get_data", "id": "9"}
]